excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

line_length:
    warning: 275
    error: 275
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

reporter: "xcode"